language: go
go:
  - tip
branches:
  only:
    - master
before_install:
  - go get github.com/kardianos/govendor
install:
  - go get -v -t -d github.com/dixonwille/wmenu
  - govendor sync
  - govendor list
